package org.inria.websmatch.db;

import java.util.List;

import org.inria.websmatch.gwt.spreadsheet.client.models.DetectionQualityData;
import org.inria.websmatch.gwt.spreadsheet.client.models.SchemaData;

public interface DBConnector {
    
    @Deprecated
    public String getXML(Integer id);
    
    @Deprecated
    public boolean insertXML(String doc);
    
    /**
     * Get the edited XML for the schema with id = object_id
     * 
     * @param object_id
     * @return Edited XML
     */      
    public String getEditedXML(String object_id, String dbName);
    
    /**
     * Insert a new XML document
     * 
     * @param auto_xml The XML generated by WebSmatch
     * @param edit_xml Edited XML
     * @param fileCompleteURI The URI of the original file
     * @return The object_id
     */
    public String insertXML(String auto_xml, String edit_xml, String fileCompleteURI, String name, String source, String user, String description, boolean ccDetectionPb, boolean attrDetectionPb, String detectPb, boolean trashed, String dbName);

    public String updateXML(String objectId, String edit_xml, String name, String description, boolean ccDetectionPb, boolean attrDetectionPb, String detectPb, boolean trashed, String dbName);
    
    public List<SchemaData> getSchemas(boolean onlyEdited, String dbName);
    
    public List<DetectionQualityData> getDetectionQualityList(boolean onlyEdited, String dbName);

    DetectionQualityData getDetectionQualityData(String objectId, String dbName);
}
